// automatically generated by the FlatBuffers compiler, do not modify
// @generated

extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod string_test {

extern crate alloc;

pub enum StringTestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StringTest<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for StringTest<'a> {
  type Inner = StringTest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> StringTest<'a> {
  pub const VT_A: ::flatbuffers::VOffsetT = 4;
  pub const VT_S: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    StringTest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StringTestArgs<'args>
  ) -> ::flatbuffers::WIPOffset<StringTest<'bldr>> {
    let mut builder = StringTestBuilder::new(_fbb);
    if let Some(x) = args.s { builder.add_s(x); }
    builder.add_a(args.a);
    builder.finish()
  }


  #[inline]
  pub fn a(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(StringTest::VT_A, Some(0)).unwrap()}
  }
  #[inline]
  pub fn s(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(StringTest::VT_S, None)}
  }
}

impl ::flatbuffers::Verifiable for StringTest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u32>("a", Self::VT_A, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("s", Self::VT_S, false)?
     .finish();
    Ok(())
  }
}
pub struct StringTestArgs<'a> {
    pub a: u32,
    pub s: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for StringTestArgs<'a> {
  #[inline]
  fn default() -> Self {
    StringTestArgs {
      a: 0,
      s: None,
    }
  }
}

pub struct StringTestBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StringTestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_a(&mut self, a: u32) {
    self.fbb_.push_slot::<u32>(StringTest::VT_A, a, 0);
  }
  #[inline]
  pub fn add_s(&mut self, s: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(StringTest::VT_S, s);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> StringTestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StringTestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<StringTest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for StringTest<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("StringTest");
      ds.field("a", &self.a());
      ds.field("s", &self.s());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `StringTest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_string_test_unchecked`.
pub fn root_as_string_test(buf: &[u8]) -> Result<StringTest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<StringTest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `StringTest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_string_test_unchecked`.
pub fn size_prefixed_root_as_string_test(buf: &[u8]) -> Result<StringTest<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<StringTest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `StringTest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_string_test_unchecked`.
pub fn root_as_string_test_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<StringTest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<StringTest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `StringTest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_string_test_unchecked`.
pub fn size_prefixed_root_as_string_test_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<StringTest<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<StringTest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a StringTest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `StringTest`.
pub unsafe fn root_as_string_test_unchecked(buf: &[u8]) -> StringTest<'_> {
  unsafe { ::flatbuffers::root_unchecked::<StringTest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed StringTest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `StringTest`.
pub unsafe fn size_prefixed_root_as_string_test_unchecked(buf: &[u8]) -> StringTest<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<StringTest>(buf) }
}
#[inline]
pub fn finish_string_test_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<StringTest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_string_test_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<StringTest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod StringTest

