// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod test {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum TestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Test<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Test<'a> {
  type Inner = Test<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Test<'a> {
  pub const VT_A: flatbuffers::VOffsetT = 4;
  pub const VT_B: flatbuffers::VOffsetT = 6;
  pub const VT_C: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Test { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TestArgs
  ) -> flatbuffers::WIPOffset<Test<'bldr>> {
    let mut builder = TestBuilder::new(_fbb);
    builder.add_c(args.c);
    builder.add_b(args.b);
    builder.add_a(args.a);
    builder.finish()
  }


  #[inline]
  pub fn a(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Test::VT_A, Some(0)).unwrap()}
  }
  #[inline]
  pub fn b(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Test::VT_B, Some(0)).unwrap()}
  }
  #[inline]
  pub fn c(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Test::VT_C, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Test<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("a", Self::VT_A, false)?
     .visit_field::<i32>("b", Self::VT_B, false)?
     .visit_field::<i32>("c", Self::VT_C, false)?
     .finish();
    Ok(())
  }
}
pub struct TestArgs {
    pub a: i32,
    pub b: i32,
    pub c: i32,
}
impl<'a> Default for TestArgs {
  #[inline]
  fn default() -> Self {
    TestArgs {
      a: 0,
      b: 0,
      c: 0,
    }
  }
}

pub struct TestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_a(&mut self, a: i32) {
    self.fbb_.push_slot::<i32>(Test::VT_A, a, 0);
  }
  #[inline]
  pub fn add_b(&mut self, b: i32) {
    self.fbb_.push_slot::<i32>(Test::VT_B, b, 0);
  }
  #[inline]
  pub fn add_c(&mut self, c: i32) {
    self.fbb_.push_slot::<i32>(Test::VT_C, c, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Test<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Test<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Test");
      ds.field("a", &self.a());
      ds.field("b", &self.b());
      ds.field("c", &self.c());
      ds.finish()
  }
}
pub enum NestingTestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NestingTest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NestingTest<'a> {
  type Inner = NestingTest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> NestingTest<'a> {
  pub const VT_A: flatbuffers::VOffsetT = 4;
  pub const VT_B: flatbuffers::VOffsetT = 6;
  pub const VT_C: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NestingTest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NestingTestArgs<'args>
  ) -> flatbuffers::WIPOffset<NestingTest<'bldr>> {
    let mut builder = NestingTestBuilder::new(_fbb);
    if let Some(x) = args.c { builder.add_c(x); }
    builder.add_b(args.b);
    builder.add_a(args.a);
    builder.finish()
  }


  #[inline]
  pub fn a(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(NestingTest::VT_A, Some(0)).unwrap()}
  }
  #[inline]
  pub fn b(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(NestingTest::VT_B, Some(0)).unwrap()}
  }
  #[inline]
  pub fn c(&self) -> Option<Test<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<Test>>(NestingTest::VT_C, None)}
  }
}

impl flatbuffers::Verifiable for NestingTest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("a", Self::VT_A, false)?
     .visit_field::<i32>("b", Self::VT_B, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<Test>>("c", Self::VT_C, false)?
     .finish();
    Ok(())
  }
}
pub struct NestingTestArgs<'a> {
    pub a: i32,
    pub b: i32,
    pub c: Option<flatbuffers::WIPOffset<Test<'a>>>,
}
impl<'a> Default for NestingTestArgs<'a> {
  #[inline]
  fn default() -> Self {
    NestingTestArgs {
      a: 0,
      b: 0,
      c: None,
    }
  }
}

pub struct NestingTestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NestingTestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_a(&mut self, a: i32) {
    self.fbb_.push_slot::<i32>(NestingTest::VT_A, a, 0);
  }
  #[inline]
  pub fn add_b(&mut self, b: i32) {
    self.fbb_.push_slot::<i32>(NestingTest::VT_B, b, 0);
  }
  #[inline]
  pub fn add_c(&mut self, c: flatbuffers::WIPOffset<Test<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<Test>>(NestingTest::VT_C, c);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NestingTestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NestingTestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NestingTest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NestingTest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NestingTest");
      ds.field("a", &self.a());
      ds.field("b", &self.b());
      ds.field("c", &self.c());
      ds.finish()
  }
}
pub enum ListTestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ListTest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ListTest<'a> {
  type Inner = ListTest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ListTest<'a> {
  pub const VT_A: flatbuffers::VOffsetT = 4;
  pub const VT_B: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ListTest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ListTestArgs<'args>
  ) -> flatbuffers::WIPOffset<ListTest<'bldr>> {
    let mut builder = ListTestBuilder::new(_fbb);
    if let Some(x) = args.b { builder.add_b(x); }
    builder.add_a(args.a);
    builder.finish()
  }


  #[inline]
  pub fn a(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ListTest::VT_A, Some(0)).unwrap()}
  }
  #[inline]
  pub fn b(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Test<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Test>>>>(ListTest::VT_B, None)}
  }
}

impl flatbuffers::Verifiable for ListTest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("a", Self::VT_A, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Test>>>>("b", Self::VT_B, false)?
     .finish();
    Ok(())
  }
}
pub struct ListTestArgs<'a> {
    pub a: i32,
    pub b: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Test<'a>>>>>,
}
impl<'a> Default for ListTestArgs<'a> {
  #[inline]
  fn default() -> Self {
    ListTestArgs {
      a: 0,
      b: None,
    }
  }
}

pub struct ListTestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ListTestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_a(&mut self, a: i32) {
    self.fbb_.push_slot::<i32>(ListTest::VT_A, a, 0);
  }
  #[inline]
  pub fn add_b(&mut self, b: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Test<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ListTest::VT_B, b);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ListTestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ListTestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ListTest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ListTest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ListTest");
      ds.field("a", &self.a());
      ds.field("b", &self.b());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Test`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn root_as_test(buf: &[u8]) -> Result<Test, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Test>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Test` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_test_unchecked`.
pub fn size_prefixed_root_as_test(buf: &[u8]) -> Result<Test, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Test>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Test` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn root_as_test_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Test<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Test<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Test` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn size_prefixed_root_as_test_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Test<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Test<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Test and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Test`.
pub unsafe fn root_as_test_unchecked(buf: &[u8]) -> Test {
  unsafe { flatbuffers::root_unchecked::<Test>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Test and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Test`.
pub unsafe fn size_prefixed_root_as_test_unchecked(buf: &[u8]) -> Test {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Test>(buf) }
}
#[inline]
pub fn finish_test_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Test<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_test_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Test<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod Test

